services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - /datawork/db:/data/db
    restart: unless-stopped
    env_file:
      - mongo.conf
#    environment:
#     MONGO_INITDB_ROOT_USERNAME: root
#     MONGO_INITDB_ROOT_PASSWORD: root
    command: [--auth]
  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
volumes:
  db:
  redis.conf: